#
# Kbuild for the vl53lx driver.
#

ccflags-y	+= -I$(src)/inc -I$(src) -I$(src)/protected/inc

ifdef DEBUG
ccflags-y	+= -DDEBUG
endif

ifdef VL53L4
ccflags-y	+= -DVL53L4
endif

ifdef VL53LX_LOG_ENABLE
ccflags-y	+= -DVL53LX_LOG_ENABLE
endif

obj-$(CONFIG_STMVL53LX)	+= stmvl53lx.o
stmvl53lx-objs		:= stmvl53lx_module.o stmvl53lx_module-i2c.o
stmvl53lx-objs		+= vl53lx_platform_ipp.o
stmvl53lx-objs		+= protected/src/vl53lx_hist_funcs.o
stmvl53lx-objs		+= protected/src/vl53lx_xtalk.o
stmvl53lx-objs		+= protected/src/vl53lx_hist_algos_gen3.o
stmvl53lx-objs		+= protected/src/vl53lx_hist_core.o
stmvl53lx-objs		+= protected/src/vl53lx_sigma_estimate.o
stmvl53lx-objs		+= protected/src/vl53lx_dmax.o
stmvl53lx-objs		+= protected/src/vl53lx_hist_algos_gen4.o
stmvl53lx-objs		+= stmvl53lx_i2c.o stmvl53lx_log.o
stmvl53lx-objs		+= src/vl53lx_api.o src/vl53lx_api_core.o
stmvl53lx-objs		+= src/vl53lx_core.o src/vl53lx_register_funcs.o
stmvl53lx-objs		+= src/vl53lx_api_preset_modes.o
stmvl53lx-objs		+= src/vl53lx_api_calibration.o
stmvl53lx-objs		+= src/vl53lx_silicon_core.o
stmvl53lx-objs		+= src/vl53lx_nvm.o
stmvl53lx-objs		+= src/vl53lx_api_debug.o src/vl53lx_core_support.o
stmvl53lx-objs		+= src/vl53lx_wait.o
stmvl53lx-objs		+= src/vl53lx_nvm_debug.o
